using System.Collections.Generic;

namespace AFPParser.StructuredFields
{
	public class MDD : StructuredField
	{
		private static string _abbr = "MDD";
		private static string _title = "Medium Descriptor";
		private static string _desc = "The Medium Descriptor structured field specifies the size and orientation of the medium presentation space for all sheets that are generated by the medium map that contains the Medium Descriptor structured field.";
		private static List<Offset> _oSets = new List<Offset>();

		public override string Abbreviation => _abbr;
		public override string Title => _title;
		protected override string Description => _desc;
		protected override bool IsRepeatingGroup => false;
		protected override int RepeatingGroupStart => 0;
		protected override List<Offset> Offsets => _oSets;

		public MDD(int length, string hex, byte flag, int sequence) : base (length, hex, flag, sequence) { }
	}
}