//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFPParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AFPParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAG,D3A8C9,Begin Active Environment Group
        ///BBC,D3A8EB,Begin Bar Code Object
        ///BDA,D3EEEB,Bar Code Data
        ///BDD,D3A6EB,Bar Code Data Descriptor
        ///BDG,D3A8C4,Begin Document Environment Group
        ///BDI,D3A8A7,Begin Document Index
        ///BDM,D3A8CA,Begin Data Map
        ///BDT,D3A8A8,Begin Document
        ///BDX,D3A8E3,Begin Data Map Transmission Subcase
        ///BFG,D3A8C5,Begin Form Environment Group (obsolete)
        ///BFM,D3A8CD,Begin Form Map
        ///BGR,D3A8BB,Begin Graphics Object
        ///BII,D3A87B,Begin Image Object IM
        ///BIM,D3A8FB,Begin Image Object IO
        ///BMM,D3A8CC, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Field_Identifiers {
            get {
                return ResourceManager.GetString("Field_Identifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # First line: Colon, then hex value (only first six characters matter)
        ///# Second line: Description
        ///# Third+ line: Colon separated groups of (Starting index, length, data type, description, and mappings) If triplets, no description is necessary
        ///#	Mappings: Comma separated values of (HEX-Mapped value) If there is a range, it will read &apos;RHEXHEX&apos; (Range, first hex to second hex)
        ///
        ///:D3A090 - TLE
        ///Assigns an attribute name and value to a page or group.
        ///0:TRIPS:
        ///
        ///:D3A6AF - PGD
        ///Specifies the size and attribu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Identifier_Info {
            get {
                return ResourceManager.GetString("Identifier_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # First line: Colon, then hex value (only first six characters matter)
        ///# Second line: Description
        ///# Third+ line: Colon separated groups of (Starting index, length, data type, description, and mappings) If triplets, no description is necessary
        ///#	Mappings: Comma separated values of (HEX-Mapped value) If there is a range, it will read &apos;RHEXHEX&apos; (Range, first hex to second hex)
        ///
        ///:D3A090 - TLE
        ///Assigns an attribute name and value to a page or group.
        ///0:TRIPS:
        ///
        ///:D3A6AF - PGD
        ///Specifies the size and attribu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PTX_Control_Sequences {
            get {
                return ResourceManager.GetString("PTX_Control_Sequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # First line: Colon, then triplet hex value (only first two characters matter)
        ///# Second line: Title
        ///# Second line: Description
        ///# Third+ line: Colon separated groups of (Starting index, data type, description, and mappings). The first two offsets are always predictable, so will not be specified here.
        ///#	Mappings: Comma separated values of (Hex value - Description). Triplet offset specific
        ///#		BITS Mappings: Comma separated values of each position of the byte (Off meaning|On Meaning)
        ///
        ///:01
        ///GCSGID/CPGID/C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Triplets {
            get {
                return ResourceManager.GetString("Triplets", resourceCulture);
            }
        }
    }
}
